base/urls.py
from django.urls import path,include
from . import views


app_name = 'base'
urlpatterns = [
    path('home',views.home,name="home"),
    path('login',views.log,name="log"),
    path('reg',views.reg,name="reg"),
    path('logo',views.logo,name="logo"),
    path('details<int:pk>',views.details,name="details"),
     path('delete_order/<int:order_id>/', views.orderdelete, name='delete_order'),
     
]

miniature/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('admindashboard/',include('admindashboard.urls')),
   
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base_templates/details.html
{%extends 'main.html'%}
{%block content%}

<div class="detailcontainer">
    <div class="image_fragement">
        <img src="{{product.product_image}}" alt="">
        
    </div>
    <div class="description_fragement">
        
        <h1>Product:{{product.product_name}}</h1>
        <h5>{{product.product_info}}</h5>
        
        <h3>Price:{{product.product_price}}$</h3>
        <h4>{{product.category.category_name}} and {{product.product_categoryofcategories.category_name}}</h4>
        <form action="" method="post">
            {%csrf_token%}
            quantity:<input type="number" id="quantity" name="quantity" min="1" max="{{product.product_stock}}"  value="1">
            <button type="submit">add to cart</button>
        </form>
        <h5>{{product.product_stock}} avaiable</h5>
        
        <div>
            <!-- for promotions of the same category -->
        </div>
    </div>
    <div>
        
        <div class="cart-container">
            {%for o in orders%}
            <div class="cart-item">
              <div class="cart-item-name">{{o.order_product.product_name}}</div>
              <div class="cart-item-price">{{o.order_product.product_price}}$</div>
              <div class="cart-item-quantity">{{o.order_count}}</div>
              <div class="btn1-class">
                <form action="{% url 'base:delete_order' o.id%}" method="post">
                    {% csrf_token %}
                    <button class="delete-button" type="submit">Delete</button>
                </form>
            </div>
            </div>
            {%endfor%}
            {%if orders%}
            <div class="btn-class"><form action="" method="post">
                {%csrf_token%}
                <button class="buy-button"  type="submit">buy</button>
            </form></div>
            {%endif%}
    </div>
</div>
{%endblock content%}

templates/base_templates/home.html
{%extends 'main.html'%}
{%block content%}


<div class="container">

    <div class="container-dictionary">
        
        {% for category in the_categories %}
        
        
        <ul>
            {% for item in dictionary %}
              {% if item.name == category %}
                {% ifchanged category %}
                  <h2>{{ category }}</h2>
                {% endifchanged %}
                <a href=""><li>{{ item.subcategory }}</li></a>
              {% endif %}
            {% endfor %}
          </ul>
      {% endfor %}
    </div>
    <div class="container-products">
      
        {%for p in products%}
       <div class="supercard">
        <div class="card1">
            <div class="card-header">
                <h3>{{p.product_name}}</h3>
                <div class="image-box">
                    <img src="{{p.product_image}}" alt="">
                  </div>
            </div>
            <div class="card-body">
                <h3>{{p.product_price}}$</h3>
                <p>{{p.product_info}}</p>
                <a class="forthebutton" href="{%url 'base:details' p.id%}"><button>Details</button></a>
            </div>
        </div>
       </div>
        
        {%endfor%}
        
    </div>
    <div></div>
</div>



{%endblock content%}

templates/base_templates/loginform.html
{%extends 'main.html'%}



{%block content%}

<div class="wrapper">
    <h2>Log In</h2>
    <form class="forms" action="" method="post">
        {%csrf_token%}
        <input type="email" name="Email" id="" placeholder="Email">
        <input type="password" name="password" id="" placeholder="password">
        
        <button type="submit">LogIn</button>
    </form>
</div>

{%endblock content%}

templates/base_templates/registerform.html
{%extends 'main.html'%}
{%block content%}
<div class="wrapper">
    <h2>Sign Up</h2>
    <form action="" method="post">
        {%csrf_token%}
        <input type="text" name="Name" id="" placeholder="Name">
        <input type="text" name="username" id="" placeholder="username">
        <input type="email" name="Email" id="" placeholder="Email">
        <input type="password" name="password" id="" placeholder="password">
        
        <button type="submit">SignUp</button>
    </form>
</div>
{%endblock content%}