base/urls.py
from django.urls import path,include
from . import views


app_name = 'base'
urlpatterns = [
    path('home',views.home,name="home"),
    path('login',views.log,name="log"),
    path('reg',views.reg,name="reg"),
    path('logo',views.logo,name="logo"),
    path('details<int:pk>',views.details,name="details"),
     path('delete_order/<int:order_id>/', views.orderdelete, name='delete_order'),
     
]

miniature/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('admindashboard/',include('admindashboard.urls')),
   
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/main.html
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>miniature</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}?v={{ version_number }}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}?v={{ version_number }}">
    <link rel="stylesheet" href="{% static 'css/details.css' %}?v={{ version_number }}">
    
</head>
<body >
    {%include 'navbar.html'%}

    
    
    {%block content%}
    {%endblock content%}
    
</body>
</html>

templates/navbar.html
{%load static%}
<link rel="stylesheet" href="{% static 'css/navbar.css'%}?v={{ version_number }}">


<header>
    <button class="rotate">logo</button>
    
    <form action="{%url 'base:home'%}" method="post">
        {%csrf_token%}
        <input type="search" name="searched" class="input" placeholder="Search a product">
        <button  type="submit">search</button>
        
    </form> 
    <nav>
        <ul class="nav_links"> 
            <li><a href="{%url 'base:home'%}">Home</a></li>
            <li class="dropdown">
                <a class="link" href="#">Categories</a>
                <div class="dropdown-menu">
                    <a href="#">Cars</a>
                    <a href="#">Trucks</a>
                    <a href="#">Planes</a>
                    <a href="#">Collections</a>
                </div>
            </li>
            <li><a href="#">Cart</a></li>
            <li><a href="#">Promotions</a></li>
        </ul>
    </nav>
    
    <nav>
        <ul class="nav_links"> 
            {%if not authent%}
            <li><a href="{%url 'base:log'%}">Login</a></li>
            <li><a href="{%url 'base:reg'%}">Register</a></li>
            {%else%}
            <li><a href="{%url 'base:logo'%}">Logout</a></li>
            {%endif%}
           
        </ul>
    </nav>
</header> 